### ISSUE TITLE
Add requirejs support

### ISSUE THREAD

**Issue by jmas** [lokesh/color-thief#65] opened 2015-04-25 20:34 UTC
Hey, guys.
It will be really nice if we add RequireJS support.
I can make Pull Request if you need this (but it seems no maintainers who can accept Pull Request, yep?).

**Comment by ksubileau** [comment] 2015-04-25 21:57
Possible duplicate of #38 ;)

**Comment by jmas** [comment] 2015-04-25 22:07
@ksubileau Yep, but not sure that this PR have enough changes for support RequireJS. I see that only 1 line is changes `var ColorThief` to `this.ColorThief`. Not sure that this PR is add support of RequireJS.

And can you explain about maintainer of this project. I see that last update was a year ago. So no maintainers who can accept my PR if I create it. Right?

**Comment by ksubileau** [comment] 2015-04-25 22:23
Right, the support on this project seems discontinued. Maybe the maintainer is working on others projects. As the developer of the [PHP port](https://github.com/ksubileau/color-thief-php), I watch this project and give help when possible, but I don't have write access (yet).

**Comment by jmas** [comment] 2015-04-25 22:32
Ok, cool! I saw your project when search some questions about ColorThief.
But it's very sad that owner of this project is disconnected.
Did you ask him to give access for you? Maybe we can email or skype him about this question?

**Comment by ksubileau** [comment] 2015-04-25 22:42
Not yet. Currently, I have not enough time for that, but maybe soon (during this summer/fall).

**Comment by jmas** [comment] 2015-04-25 22:50
@ksubileau I sure that support this JS lib is not hard. So 2 collaborator that can accept PR are more productive for project than nobody.
So I only let you know that I can do some work for review / manage PR, write test etc. We need ask @lokesh about this.

**Comment by lokesh** [comment] 2019-07-15 04:53
CommonJS, AMD, and ES6 module support was added... finally. 😅 
https://github.com/lokesh/color-thief/releases

**Closed by lokesh** 2019-07-15 04:53 UTC
Labels: module
